version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: 'mycontainer'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: mediafile
      MONGO_INITDB_ROOT_PASSWORD: arhamsoft
    
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: arhamsoft
      ME_CONFIG_MONGODB_URL: mongodb://root:arhamsoft@mongo:27017/  
   